var mongodb = require('mongodb');
var tracking = require('../tracking');
var emailer = require('../emailer');

module.exports = function (test) {
    await mongodb.connect('mongodb://localhost/awaitdefer', defer(error, db));
    if (error) throw error;

    var orderId = 1;
    await db.collection('orders').findOne(orderId, defer (error, order));
    if (error) throw error;

    await {
        db.collection('users').findOne(order.customer.id, defer (error, user));
        tracking.track(order.trackingId, defer (error2, trackingInformation));
    }
    if (error || error2) throw error || error2;
    db.close();

    var message = {
        subject: 'Order: ' + order.name,
        email: user.email,
        body: 'Tracking: ' + trackingInformation
    };
    await emailer.sendEmail(message, defer (error));
    if (error) throw error;

    test.done();
};